export const COMMON_STOCKS = [
    { symbol: 'RELIANCE.NS', shortname: 'Reliance Industries Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'TCS.NS', shortname: 'Tata Consultancy Services Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'HDFCBANK.NS', shortname: 'HDFC Bank Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'ICICIBANK.NS', shortname: 'ICICI Bank Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'BHARTIARTL.NS', shortname: 'Bharti Airtel Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'SBIN.NS', shortname: 'State Bank of India', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'INFY.NS', shortname: 'Infosys Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'LICI.NS', shortname: 'Life Insurance Corporation of India', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'ITC.NS', shortname: 'ITC Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'HINDUNILVR.NS', shortname: 'Hindustan Unilever Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'LT.NS', shortname: 'Larsen & Toubro Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'BAJFINANCE.NS', shortname: 'Bajaj Finance Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'HCLTECH.NS', shortname: 'HCL Technologies Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'MARUTI.NS', shortname: 'Maruti Suzuki India Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'SUNPHARMA.NS', shortname: 'Sun Pharmaceutical Industries Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'ADANIENT.NS', shortname: 'Adani Enterprises Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'KOTAKBANK.NS', shortname: 'Kotak Mahindra Bank Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'TITAN.NS', shortname: 'Titan Company Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'ONGC.NS', shortname: 'Oil and Natural Gas Corporation Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'TATAMOTORS.NS', shortname: 'Tata Motors Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'NTPC.NS', shortname: 'NTPC Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'AXISBANK.NS', shortname: 'Axis Bank Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'DMART.NS', shortname: 'Avenue Supermarts Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'ADANIGREEN.NS', shortname: 'Adani Green Energy Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'ADANIPORTS.NS', shortname: 'Adani Ports and Special Economic Zone Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'ULTRACEMCO.NS', shortname: 'UltraTech Cement Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'ASIANPAINT.NS', shortname: 'Asian Paints Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'COALINDIA.NS', shortname: 'Coal India Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'BAJAJFINSV.NS', shortname: 'Bajaj Finserv Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'BAJAJ-AUTO.NS', shortname: 'Bajaj Auto Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'POWERGRID.NS', shortname: 'Power Grid Corporation of India Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'NESTLEIND.NS', shortname: 'Nestle India Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'WIPRO.NS', shortname: 'Wipro Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'M&M.NS', shortname: 'Mahindra & Mahindra Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'IOC.NS', shortname: 'Indian Oil Corporation Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'JIOFIN.NS', shortname: 'Jio Financial Services Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'HAL.NS', shortname: 'Hindustan Aeronautics Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'DLF.NS', shortname: 'DLF Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'TATASTEEL.NS', shortname: 'Tata Steel Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'SIEMENS.NS', shortname: 'Siemens Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'VBL.NS', shortname: 'Varun Beverages Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'ZOMATO.NS', shortname: 'Zomato Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'PIDILITIND.NS', shortname: 'Pidilite Industries Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'GRASIM.NS', shortname: 'Grasim Industries Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'SBILIFE.NS', shortname: 'SBI Life Insurance Company Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'BEL.NS', shortname: 'Bharat Electronics Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'LTIM.NS', shortname: 'LTIMindtree Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'TRENT.NS', shortname: 'Trent Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'PNB.NS', shortname: 'Punjab National Bank', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'INDIGO.NS', shortname: 'InterGlobe Aviation Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'BANKBARODA.NS', shortname: 'Bank of Baroda', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'HDFCLIFE.NS', shortname: 'HDFC Life Insurance Company Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'ABB.NS', shortname: 'ABB India Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'BPCL.NS', shortname: 'Bharat Petroleum Corporation Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'PFC.NS', shortname: 'Power Finance Corporation Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'GODREJCP.NS', shortname: 'Godrej Consumer Products Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'TATAPOWER.NS', shortname: 'Tata Power Company Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'HINDALCO.NS', shortname: 'Hindalco Industries Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'HAL.NS', shortname: 'Hindustan Aeronautics Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'VEDL.NS', shortname: 'Vedanta Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'VOLTAS.NS', shortname: 'Voltas Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'ZENTEC.NS', shortname: 'Zen Technologies Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'IREDA.NS', shortname: 'Indian Renewable Energy Development Agency Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'RVNL.NS', shortname: 'Rail Vikas Nigam Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'IRFC.NS', shortname: 'Indian Railway Finance Corporation Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'MAZDOCK.NS', shortname: 'Mazagon Dock Shipbuilders Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'BHEL.NS', shortname: 'Bharat Heavy Electricals Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'CGPOWER.NS', shortname: 'CG Power and Industrial Solutions Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'JSWSTEEL.NS', shortname: 'JSW Steel Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'CHOLAFIN.NS', shortname: 'Cholamandalam Investment and Finance Company Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'AMBUJACEM.NS', shortname: 'Ambuja Cements Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'TECHM.NS', shortname: 'Tech Mahindra Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'CIPLA.NS', shortname: 'Cipla Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'SHREECEM.NS', shortname: 'Shree Cement Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'TVSMOTOR.NS', shortname: 'TVS Motor Company Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'EICHERMOT.NS', shortname: 'Eicher Motors Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'DRREDDY.NS', shortname: 'Dr. Reddy\'s Laboratories Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'WIPRO.NS', shortname: 'Wipro Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'BOSCHLTD.NS', shortname: 'Bosch Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'MANKIND.NS', shortname: 'Mankind Pharma Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'ZYDUSLIFE.NS', shortname: 'Zydus Lifesciences Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'M&MFIN.NS', shortname: 'Mahindra & Mahindra Financial Services Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'BERGEPAINT.NS', shortname: 'Berger Paints (I) Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'ICICIPRULI.NS', shortname: 'ICICI Prudential Life Insurance Company Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'AWL.NS', shortname: 'Adani Wilmar Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'DIXON.NS', shortname: 'Dixon Technologies (India) Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'MAXHEALTH.NS', shortname: 'Max Healthcare Institute Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'AUBANK.NS', shortname: 'AU Small Finance Bank Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'PHARMA.NS', shortname: 'Sun Pharma', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'CONCOR.NS', shortname: 'Container Corporation of India Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'PETRONET.NS', shortname: 'Petronet LNG Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'IGL.NS', shortname: 'Indraprastha Gas Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'MGL.NS', shortname: 'Mahanagar Gas Limited', exchange: 'NSE', quoteType: 'EQUITY' },
    { symbol: 'MUTHOOTFIN.NS', shortname: 'Muthoot Finance Limited', exchange: 'NSE', quoteType: 'EQUITY' }
];
